---
port: 3000
timeout: 30
wait: 30
pid: tmp/pids/thin.pid
log: log/thin.log
max_conns: 1024
environment: production
max_persistent_conns: 512
servers: 1
threaded: true
daemonize: true
tag: ruby_evin_upstream
